version: "3.5"

services:
    web:
        build:
            context: "."
            target: "dev"
            args:
                DDE_UID: ${DDE_UID}
                DDE_GID: ${DDE_GID}
        environment:
            - VIRTUAL_HOST=visualization.test
        volumes:
            - ./:/var/www
        restart: always

networks:
    default:
        name: "dde"
        external: true
